### ISSUE TITLE
需要训练多少epoch收敛，并达到与论文近似的结果

### ISSUE THREAD

**Issue by jiaohuix** [gpengzhi/CrossConST-MT#1]
请问m-transformer和cross_const训练各自需要多少个epoch才能收敛，并在英德上取得与表格相当的效果。
目前我训练了baseline 43轮，似乎无法再下降了，我试了评估下英德的分数，但只有1.4分，请问还需要继续训练吗？

![image](https://github.com/gpengzhi/CrossConST-MT/assets/68314259/5ec05dc3-3511-47b9-970c-0b0ece988ea3)
![d16514003234ea9c64cacf276d0004e](https://github.com/gpengzhi/CrossConST-MT/assets/68314259/0ab96d0c-1932-4bd7-8357-06d2a737fb5d)

epoch 043:  11083 / 11763 loss=6.529, nll_loss=5.227, ppl=37.44, wps=89799.4, ups=24.76, wpb=3626.3, bsz=156, num_updates=505100, lr=6.2293e-05, gnorm=3.613, loss_scale=2, train_wall=4, gb_free=21.1, wall=21380

**Comment by gpengzhi** [comment]
你是严格按照README里提供的流程进行训练的吗？从training loss上看收敛不太正常。

具体epoch数我记不清了，但是对于m-Transformer来说，43个epoch应该可能基本能得到一个『还可以的』BLEU 分数。BLEU分数1.4应该是你的实验哪里有问题，而不是训练本身不充分。

**Comment by jiaohuix** [comment]
我找到问题了大佬，我用的单卡bsz=4096，现在设置为bsz=8192 update-freq=4就正常收敛了。

```python

EXP=iwslt17_baseline
DATA=data-bin/iwslt17.tokenized

mkdir -p checkpoint/$EXP
mkdir -p log/$EXP

CUDA_VISIBLE_DEVICES=0 fairseq-train $DATA \
    --user-dir ./user_src --update-freq 4  --max-epoch 150 --keep-best-checkpoints 3 \
    --arch transformer_wmt_en_de --share-all-embeddings \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 4000 \
    --lr 0.0007 --stop-min-lr 1e-09 --dropout 0.3 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --weight-decay 0.0 \
    --max-tokens 8192 --fp16 --no-epoch-checkpoints --tensorboard-logdir log/$EXP/vislog/ --save-dir checkpoint/$EXP \
    1>log/$EXP/log.out 2>log/$EXP/log.err

```

![image](https://github.com/gpengzhi/CrossConST-MT/assets/68314259/e29c02f9-d797-45aa-8014-96e646b2a9ca)
![1f738244d4f73d04b70827c9838fc70](https://github.com/gpengzhi/CrossConST-MT/assets/68314259/893bc9d1-4e56-47da-93b5-c4538a181f36)

但是现在训练cross_const时候出现了loss scale太小导致训练停止的问题，这个有什么方法解决吗？
```python
EXP=iwslt17_crossconst_alpha025
DATA=data-bin/iwslt17.tokenized
CKPT=checkpoint/iwslt17_baseline_8/checkpoint_best.pt

mkdir -p checkpoint/$EXP
mkdir -p log/$EXP

CUDA_VISIBLE_DEVICES=0 fairseq-train $DATA \
    --user-dir ./user_src --update-freq 4  --max-epoch 150 --keep-best-checkpoints 3 \
    --arch transformer_wmt_en_de --share-all-embeddings \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 4000 \
    --lr 0.00007 --stop-min-lr 1e-09 --dropout 0.3 \
    --criterion label_smoothed_cross_entropy_with_crossconst --alpha 0.25 --label-smoothing 0.1 --weight-decay 0.0 \
    --reset-optimizer --reset-meters --reset-dataloader --reset-lr-scheduler --restore-file $CKPT \
    --max-tokens 8192 --fp16 --no-epoch-checkpoints --tensorboard-logdir log/$EXP/vislog/ --save-dir checkpoint/$EXP \
    1>log/$EXP/log.out 2>log/$EXP/log.err


```

2024-03-03 11:15:31 | INFO | fairseq.trainer | NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.000244140625
epoch 001:   1%|█▋                                                                                                                                   | 19/1456 [00:29<35:54,  1.50s/it]2024-03-03 11:15:32 | INFO | fairseq.trainer | NOTE: gradient overflow detected, ignoring gradient, setting loss scale to: 0.0001220703125
epoch 001:   1%|█▊                                                                                                                                   | 20/1456 [00:31<35:18,  1.48s/it]2024-03-03 11:15:34 | INFO | fairseq.trainer | Saving checkpoint to /home/rid/Projects/DB-GPT-Hub/nmt/mnmt/CrossConST-MT/checkpoint/iwslt17_crossconst_alpha025/crash.pt
2024-03-03 11:15:34 | INFO | fairseq.trainer | Finished saving checkpoint to /home/rid/Projects/DB-GPT-Hub/nmt/mnmt/CrossConST-MT/checkpoint/iwslt17_crossconst_alpha025/crash.pt
/home/rid/miniconda3/envs/resdsql/lib/python3.8/site-packages/torch/nn/modules/module.py:1359: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
/home/rid/miniconda3/envs/resdsql/lib/python3.8/site-packages/torch/nn/modules/module.py:1324: UserWarning: Using non-full backward hooks on a Module that does not return a single Tensor or a tuple of Tensors is deprecated and will be removed in future versions. This hook will be missing some of the grad_output. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using non-full backward hooks on a Module that does not return a "
Traceback (most recent call last):                                                                                                                                                     
  File "/home/rid/Projects/DB-GPT-Hub/fairseq/fairseq/trainer.py", line 953, in train_step
    grad_norm = self.clip_grad_norm(self.cfg.optimization.clip_norm)
  File "/home/rid/Projects/DB-GPT-Hub/fairseq/fairseq/trainer.py", line 1295, in clip_grad_norm
    return self.optimizer.clip_grad_norm(
  File "/home/rid/Projects/DB-GPT-Hub/fairseq/fairseq/optim/fp16_optimizer.py", line 206, in clip_grad_norm
    self.scaler.check_overflow(grad_norm)
  File "/home/rid/Projects/DB-GPT-Hub/fairseq/fairseq/optim/dynamic_loss_scaler.py", line 61, in check_overflow
    raise FloatingPointError(
FloatingPointError: Minimum loss scale reached (0.0001). Your loss is probably exploding. Try lowering the learning rate, using gradient clipping or increasing the batch size.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rid/miniconda3/envs/resdsql/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/home/rid/Projects/DB-GPT-Hub/fairseq/fairseq_cli/train.py", line 574, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/rid/Projects/DB-GPT-Hub/fairseq/fairseq/distributed/utils.py", line 404, in call_main
    main(cfg, **kwargs)
  File "/home/rid/Projects/DB-GPT-Hub/fairseq/fairseq_cli/train.py", line 205, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/rid/miniconda3/envs/resdsql/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/rid/Projects/DB-GPT-Hub/fairseq/fairseq_cli/train.py", line 331, in train
    log_output = trainer.train_step(samples)
  File "/home/rid/miniconda3/envs/resdsql/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/rid/Projects/DB-GPT-Hub/fairseq/fairseq/trainer.py", line 1000, in train_step
    self.task.train_step(
  File "/home/rid/Projects/DB-GPT-Hub/fairseq/fairseq/tasks/fairseq_task.py", line 532, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/rid/miniconda3/envs/resdsql/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/rid/miniconda3/envs/resdsql/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rid/Projects/DB-GPT-Hub/nmt/mnmt/CrossConST-MT/user_src/label_smoothed_cross_entropy_with_crossconst.py", line 125, in forward
    net_output = model(**sample["net_input"])
  File "/home/rid/miniconda3/envs/resdsql/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/rid/miniconda3/envs/resdsql/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/rid/Projects/DB-GPT-Hub/fairseq/fairseq/models/transformer/transformer_base.py", line 161, in forward
    encoder_out = self.encoder(
  File "/home/rid/miniconda3/envs/resdsql/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/rid/miniconda3/envs/resdsql/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1598, in _call_impl
    var = next(v for v in var.values() if isinstance(v, torch.Tensor))
StopIteration

**Comment by gpengzhi** [comment]
你可以先尝试去掉 fp16，看看能否得到和我相近的结果。

**Comment by jiaohuix** [comment]
ok 只不过训练的好像有点慢，原先fp16 5分钟一轮，现在变成1.5h一轮了，这个速度正常吗

![Uploading image.png…]()

**Comment by gpengzhi** [comment]
不正常 看一下是不是出现OOM了

**Comment by jiaohuix** [comment]
应该是的，用了amp也要三四十分钟，还是挺慢。另外，baseline训练了120epoch差不多收敛，cross-const需要训练多久额

**Comment by gpengzhi** [comment]
CrossConST 因为会同一个batch feedforward两次，所以其对显存的要求比vanilla training要大，请适当减小batch size以避免OOM。具体epoch数应该会比120epoch少一些。

**Comment by jiaohuix** [comment]
![c4b742c829010f411038bde6d797d97](https://github.com/gpengzhi/CrossConST-MT/assets/68314259/f9647d26-b6c0-45dc-94ae-1a9d98b41610)

ok大佬，已经复现了结果，谢谢哈。另外方便共享下评估多语言的脚本嘛~

baseline训练了150epoch，120左右收敛，4090 大约5min/epoch；CrossConST训练了10轮左右，fp16会报错换成了amp，大概20-30min/epoch。训练脚本如下：

```python

EXP=iwslt17_baseline
DATA=data-bin/iwslt17.tokenized

mkdir -p checkpoint/$EXP
mkdir -p log/$EXP

CUDA_VISIBLE_DEVICES=0 fairseq-train $DATA \
    --user-dir ./user_src --update-freq 4  --max-epoch 150 --keep-best-checkpoints 3 \
    --arch transformer_wmt_en_de --share-all-embeddings \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 4000 \
    --lr 0.0007 --stop-min-lr 1e-09 --dropout 0.3 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --weight-decay 0.0 \
    --max-tokens 8192 --fp16 --no-epoch-checkpoints --tensorboard-logdir log/$EXP/vislog/ --save-dir checkpoint/$EXP \
    1>log/$EXP/log.out 2>log/$EXP/log.err

```



```python

EXP=iwslt17_crossconst_alpha025
DATA=data-bin/iwslt17.tokenized
CKPT=checkpoint/iwslt17_baseline/checkpoint_best.pt

mkdir -p checkpoint/$EXP
mkdir -p log/$EXP

CUDA_VISIBLE_DEVICES=0 fairseq-train $DATA \
    --user-dir ./user_src --update-freq 8  --max-epoch 150 --keep-best-checkpoints 3 \
    --arch transformer_wmt_en_de --share-all-embeddings \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 4000 \
    --lr 0.00007 --stop-min-lr 1e-09 --dropout 0.3 \
    --criterion label_smoothed_cross_entropy_with_crossconst --alpha 0.25 --label-smoothing 0.1 --weight-decay 0.0 \
    --reset-optimizer --reset-meters --reset-dataloader --reset-lr-scheduler --restore-file $CKPT \
    --max-tokens 4096 --amp --no-epoch-checkpoints --tensorboard-logdir log/$EXP/vislog/ --save-dir checkpoint/$EXP \
    1>log/$EXP/log.out 2>log/$EXP/log.err


```

**Comment by gpengzhi** [comment]
目前没有多语言的脚本，你可以按照我提供的英到德的脚本自己写一个，应该没有本质区别。

**Comment by jiaohuix** [comment]
好的大佬，我测测看
